language: csharp
mono: 5.2.0.215
dist: trusty
script:
 - mono .nuget/nuget.exe restore
 - msbuild EU4.Savegame.sln
 - '(cd EU4.Savegame.Test/bin && mono ../../packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe EU4.Savegame.Test.dll)'
 - '(cd EU4.Stats.Web.Test/bin && mono ../../packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe EU4.Stats.Web.Test.dll)'
 - '(cd EU4.Stats.Test/bin && mono ../../packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe EU4.Stats.Test.dll)'

